home/urls.py
from django.urls import path

from . import views
from django.urls import path, include

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('home', views.home, name='home'),
    path('bio', views.bio, name='bio'),
    path('socmed', views.socmed, name='socmed'),
    path('studies', views.studies, name='studies'),
    path('story1', views.story1, name='story1'),
]

kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import fungsi_suatu_url, fungsi_data
from login import views as s

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('schedule', include('schedule.urls')),
    path('kegiatan/',include('kegiatan.urls',namespace = 'templates')),
    path('story7/', include(('story7.urls','story7'), namespace = 'story7')),
    path('story8/', fungsi_suatu_url),
    path('data/', fungsi_data),
    path('login/', s.loginPage, name='login'),
    path('logout/', s.logoutUser, name='logout'),
    path('register/', s.register, name='register'),
    path('landing/', s.landing, name='landing'),
    path('', include("django.contrib.auth.urls")),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.add, name='addschedule'),
    path('delete/<str:pk>/',views.delete, name='delete'),
]

story7/urls.py
from django.urls import path
from .views import index


appname = 'Story7'

urlpatterns = [
   path('', index, name = 'accordion'),
]

home/models.py
from django.db import models

kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan= models.CharField(max_length=30)
    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan,null = True, on_delete= models.SET_NULL)

    def __str__(self):
        return self.nama_peserta
    

login/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    matkul = models.CharField(max_length=120)
    dosen = models.CharField(max_length=120)
    sks = models.CharField(max_length=30)
    deskripsi = models.CharField(max_length=200)
    semester = models.CharField(max_length=20)
    ruang = models.CharField(max_length=20)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

home/forms.py
from .models import Jadwal
from django import forms

kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields ="__all__"
    

class formPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = "__all__"

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
	    model = User
	    fields = ["username", "email", "password1", "password2"]

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def home(request):
    return render(request, 'home/home.html')

def bio(request):
    return render(request, 'home/bio.html')

def socmed(request):
    return render(request, 'home/socmed.html')

def studies(request):
    return render(request, 'home/studies.html')

def story1(request):
    return render(request, 'home/index.html')

kegiatan/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan,Peserta
from .forms import formKegiatan,formPeserta

# Create your views here.
def list_kegiatan(request):
    list_kegiatan = Kegiatan.objects.all()
    data_kegiatan = []
    for kegiatan in list_kegiatan:
        list_peserta = Peserta.objects.filter(kegiatan=kegiatan)
        data_peserta = []
        for peserta in list_peserta:
            data_peserta.append(peserta)
        data_kegiatan.append((kegiatan,data_peserta))
    context = {'data_kegiatan':data_kegiatan,'number':5}
    return render(request,'kegiatan.html',context)


def tambah_peserta(request):
    form = formPeserta()
    if (form.is_valid and request.method == 'POST'):
        form = formPeserta(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form,'number':5}
    return render(request,'tambahpeserta.html',context)

def tambah_kegiatan(request):
    form = formKegiatan()
    if (form.is_valid and request.method == 'POST'):
        form = formKegiatan(request.POST)
        form.save()
        return redirect('/kegiatan')

    context = {'form':form,'number':5}
    
    return render(request,'tambahkegiatan.html',context)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = RegisterForm()
        if request.method == "POST":
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect("/login/")
            
        return render(request, "register.html", {"form":form})

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/landing/')
            else:
                return render(request,'login.html', {
                    'error_message': ' Login Failed! Enter the username and password correctly', })

        context = {'number':8}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/login/')

def landing(request):
    return render(request, 'landing.html')

schedule/views.py
from django.shortcuts import render, redirect

from .models import Jadwal
# Create your views here.

def add(request):
    param = False
    
    sdata = Jadwal.objects.all()

    if request.method == "POST" :
        param = True 
        matakuliah = request.POST.get("nama")
        semesterv = request.POST.get("semester")
        sksv = request.POST.get("sks")
        dosenv = request.POST.get("dosen")
        ruangv = request.POST.get("ruang")
        deskripsiv = request.POST.get("deskripsi")
        p = Jadwal.objects.create(matkul = matakuliah, dosen = dosenv, sks = sksv, deskripsi = deskripsiv, semester = semesterv, ruang = ruangv)
        p.save()

    context = {
        'par' : param,
        'send': sdata
    }
    return render(request, 'jadwal.html',context)

def delete(request, pk):
    item=Jadwal.objects.get(id=pk)
    if request.method == "POST":
        item.delete()
        return redirect("/schedule")
    context ={
        'matkulv': item,
    }
    return render(request,'remove.html',context)

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    response = {}
    return render(request,'story7.html',response)

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json

# Create your views here.
def fungsi_suatu_url(request):
    response = {}
    return render(request, 'search.html', response)

def fungsi_data(request):
    arg = request.GET['q']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(url_tujuan)

    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

home/templates/home/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>

        <a id ="bio" href="bio">Bio </a>
        <a id="home" href="home">Home</a>
        <a id="socmed" href="socmed">Socmed</a>
        <a id="studies" href="studies">Studies</a>
        <a id ="story1" href="story1">Story1</a>
        <a id ="schedule" href="{% url 'schedule:addschedule' %}">schedule</a>
        

        {% block content %}
        {% endblock %}
    </div>
  </div>
</body>
</html>

home/templates/home/bio.html
<!DOCTYPE html>
<html>
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
  <div class="row">
    <div class="column left" id="kolom_gambar2">
    </div>
    <div class="column right" style="background-color:#1F1F1F;"></div>
        <div id ="judulbio"> Bio </div>
        <div id ="linebio"></div>
        <div id ="linebio2"></div>
        <div class="center1">
            <p style="text-align: center;"></p>
            Name : Andika Prasetya <br>
            <br>
            NPM : 1906400305 <br>
            <br>
            Occupation : College Student <br>
            <br>
            Study at : University of Indonesia <br>
            <br>
            Faculty : Faculty of Computer Science <br>
            <br>
            Hobby : Games, Sports <br>
            </p>
        </div>
    </div>

  </div>
</body>
{% endblock %}
</html>

home/templates/home/home.html
<!DOCTYPE html>
<html>
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
  <div class="row">
    <div class="column left" style="background-color:#1F1F1F;">
        <div id ="judul"> Welcome to My Website </div>
        <div id ="line1"></div>
        <div id ="line2"></div>
    </div>
    <div class="column right" id="kolom_gambar">
    </div>
  </div>
</body>
{% endblock %}
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylestory1.css' %}" />
    <title>My Profile</title>
</head>
<body>
    <div style="margin: 360px"></div>
    <div class="column left">
    <div class="header">
        <h1>Welcome to My Profile</h1>
    </div>
    <div class="row">
        <h2>Bio</h2>
        <img src="static/home/dika.jpg", width="200px" height="300px">
        <h3><b> Name </b>: Andika Prasetya</h3>
        <p><b> NPM </b>: 1906400305</p>
        <p><b> Hobby </b>: Sports, Games</p>
        <p><b> Desc </b>: Masih berusaha untuk bisa membuat web kedepannya </p>
        <p><b> Riwayat Pendidikan </b>:</p>

		<table>
			<tr>
				<th> <b> Tahun </b> </th>
				<th> <b> Nama Sekolah </b> </th>
			</tr>
			<tr>
				<td> 2019-Sekarang </td>
				<td> Universitas Indonesia </td>
			</tr>
			<tr>
				<td> 2016-2019 </td>
				<td> SMA Kristen 3 Penabur Jakarta</td>
			</tr>
			<tr>
				<td> 2013-2016 </td>
				<td> SMP Kristen 3 Penabur </td>
			</tr>
			<tr>
				<td> 2007-2013 </td>
				<td> SD Marsudirini Matraman </td>
			</tr>
        </table>
        
        <br>

        <h3>Social Media</h3>
        <h5>My Instagram and Facebook</h5>
        <a href ="https://www.instagram.com/andika_pras7/">
        <img src="static/home/instagram.jpg", width="50px" height="50px">
        </a>
        <a href="https://www.facebook.com/andika.prasetya.988">
        <img src="static/home/facebook.jpg", width="50px" height="50px">
        </a>
    </div>
    </div>
</body>
{% endblock %}
</html>

home/templates/home/socmed.html
<!DOCTYPE html>
<html>
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
  <div class="row">
    <div class="column left" style="background-color:#1F1F1F;">
        <div class="center2">
            <p style="text-align: center;"></p>
            Social <br>
            &nbsp&nbsp&nbsp&nbspMedia <br>
        </div>
        <img id="insta" src="/static/home/instagram.jpg" alt="insta logo">
        <div id ="instad"> Instagram&nbsp:&nbsp@andika_pras7 </div>
        <img id="line" src="/static/home/line.jpg" alt="line logo">
        <div id ="lined"> Line&nbsp:&nbspandika1st </div>
        <img id="wa" src="/static/home/wa.jpg" alt="wa logo">
        <div id ="wad"> Whatsapp&nbsp:&nbsp+62&nbsp812&nbsp9094&nbsp3824 </div>
    </div>
    <div class="column right" id="kolom_gambar3">
    </div>
  </div>
</body>
{% endblock %}
</html>

home/templates/home/studies.html
<!DOCTYPE html>
<html>
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
  <div class="row">
    <div class="column left" id="kolom_gambar4">
    </div>
    <div class="column right" style="background-color:#1F1F1F;"></div>
        <div id ="judulbio"> School </div>
        <div id ="linebio"></div>
        <div id ="linebio2"></div>
        <div class="center1">
            <p style="text-align: center;"></p>
            SD Marsudirini <br>
            <br>
            SMP Kristen 3 Penabur <br>
            <br>
            SMA Kristen 3 Penabur <br>
            <br>
            University of Indonesia <br>
            </p>
        </div>
    </div>
  </div>
</body>
{% endblock %}
</html>

kegiatan/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
        {% block content %}
        {% endblock %}

</body>
</html>

kegiatan/templates/kegiatan.html
<!doctype html>
<html lang="en">
  {% extends "base.html" %}
  {% load static %}
  {% block content %}
  
  <main>
    <section class="section-1">
        
      <div class = "container text-center">
        <div class="text-right"><a class="btn btn-sm btn-info" href="tambahkegiatan">Tambah Kegiatan</a></div>
        <h1 class="text-center">
            Daftar Kegiatan
        </h1>
          <div class="row">

            {% for i in data_kegiatan %}
              <div class="card" style="width: 50%;">
                  <div class="card-body">
                    
                    <h5 class="card-title mb-3">{{i.0.nama_kegiatan}}</h5>
                    <p class="card-text">
                        {% for a in i.1 %}
                        <div>{{a.nama_peserta}}</div>
                        {% endfor %}
                        </p>
                        
                        
                </div>
          </div>
          {% endfor %}
          
        </div>
        <br>
        <div class="text-center"><a class="btn btn-sm btn-info" href="{% url 'templates:tambahpeserta' %}">Tambah Peserta</a></div>
        <br><br><br><br><br><br>
    </div>
</div>
    
  </main>
  {% endblock %}

kegiatan/templates/tambahkegiatan.html
{% extends "base.html" %}
  {% load static %}
  {% block content %}
  <div style="margin: 450px"></div>

<form action="" method="post">
    {% csrf_token %}
{{form}}
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Tambah">
<a class="btn btn-lg btn-block btn-info" href="/kegiatan">Batal</a>
</form>
{% endblock %}

kegiatan/templates/tambahpeserta.html
<form action="" method="post">
    {% csrf_token %}
{{form}}
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Tambah">
</form>

login/templates/landing.html
<head>
<title>Story9</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<body>
    {% if user.is_authenticated %}
        Hello  {{request.user}}
        {% endif %}
    <a href="{% url 'logout' %}" class="ml-2">Logout</a>
</body>
</head>

login/templates/login.html
<head>
	<title>Story9</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
		}

		body{
            background:rgb(240, 219, 35);
            padding-bottom: 65vw;
            background-size: cover;
            font-family: Arial, Helvetica, sans-serif;
        }
		.user_card {
			width: 350px;
			margin-top: 200px;
			margin-bottom: auto;
			background: white;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #7abecc;
			
		}

		.login_btn {
			width: 100%;
			background: white;
			color: #7abecc;
		}
		.login_btn:focus {
			box-shadow: none;
			outline: 0px;
		}
		.login_container {
			padding: 0 2rem;
		}
		

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password" class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

					<p class ="text-center">{{error_message}}</p>
					
				{%for message in messages%}
					<div class="alert alert-success d-flex justify-content-center mt-3" role="alert" style="font-size: 0.8em;">
						{{message}}
					</div>
					{%endfor%}
		
		

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

schedule/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <!-- Extra Fonts and Icon -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
</head>
<body>
        {% block content %}
        {% endblock %}

</body>
</html>

schedule/templates/jadwal.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'schedule:addschedule' %}" method="POST">{% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputEmail4">mata kuliah</label>
        <input type="text" class="form-control" name="nama">
      </div>
      <div class="form-group col-md-6">
        <label for="inputPassword4">semester</label>
        <input type="text" class="form-control" name="semester">
      </div>
    </div>
    <div class="form-group">
      <label for="inputAddress">dosen</label>
      <input type="text" class="form-control" name="dosen">
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">ruang</label>
        <input type="text" class="form-control" name="ruang">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">sks</label>
          <input type="text" class="form-control" name="sks">
        </div>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">deskripsi</label>
        <textarea class="form-control" name="deskripsi" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  

  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">nomor</th>
        <th scope="col">mata kuliah</th>
        <th scope="col">semester</th>
        <th scope="col">dosen</th>
        <th scope="col">ruang</th>
        <th scope="col">sks</th>
        <th scope="col">deskripsi</th>
      </tr>
    </thead>
    <tbody>
      {% for i in send %}
      <tr>
        <td>{{i.id}}</td>
        <td>{{i.matkul}}</td>
        <td>{{i.semester}}</td>
        <td>{{i.dosen}}</td>
        <td>{{i.ruang}}</td>
        <td>{{i.sks}}</td>
        <td>{{i.deskripsi}}</td>
        <td><a class="btn btn-outline-danger" value="Delete" href="{% url 'schedule:delete' i.id %}">remove</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

schedule/templates/remove.html
{% extends 'base.html' %} {% load static %} 
<title>My Schedule</title>
{% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="container-fluid">
        <div class="halaman">
            <h2>Apakah kamu ingin menghapus {{matkulv.matkul}}</h2>

            <form action="." method="POST">{% csrf_token %}
                <a class="btn btn-outline-primary" href="{% url 'schedule:addschedule' %}">Cancel</a>
                <input class="btn btn-outline-danger" type="submit" Value="Confirm" name="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}